### ISSUE TITLE
Support HTTPS for local endpoints

### ISSUE THREAD

**Issue by mbyczkowski** [superfly/wormhole#31]
Right now we only support HTTP for communication between wormhole client/agent and local endpoint. There's no reason why we wouldn't allow HTTPS connections. Especially that the wormhole agent might not be deployed on the same server as the local endpoint.

It's possible that people might want to use self-signed certificates, so we should have an option for `InsecureSkipVerify` and/or `CAfile`

**Comment by doodles526** [comment]
Implemented with #32
