### ISSUE TITLE
Expose endpoints over single port (w/ TLS)

### ISSUE THREAD

**Issue by mrkurt** [superfly/wormhole#35]
This will replace the "assign a port for new wormhole connections" function with a single TLS'd port. 

When an agent connects to the wormhole server, the server should generate a unique identifier for that endpoint.

When our proxy wants to connect to a specific endpoint, it will connect to something like: `<identifier>.wormhole.server.com:443` with TLS

Wormhole server should:

1. Accept the connection
2. Lookup the endpoint using SNI
3. Validate the proxy's client certificate for that particular endpoint/backend.

This will simplify how we use wormhole substantially. Right now, we have to run an additional "backhaul" proxy to bounce connections around internally.

**Comment by jeromegn** [comment]
Definitely.

I would do something like: `<identifier>.<cluster_url>` the `cluster_url` would contain the region and information. Else it'd be hard to point to the right wormhole server.

**Comment by doodles526** [comment]
Closed with #38
